- package.json
- pnpm-lock.yaml
- src/pages/api/v1/web3up/allowlist.ts
- src/pages/api/v1/web3up/metadata.ts
- src/utils/getFromIPFS.ts
- test/api/v1/allowlist.test.ts
- test/utils/cids.ts
- test/utils/index.ts
- test/utils/mockMerkleTree.ts
- tsconfig.json
* allowlist upload
* validate allowlist in metadata
* more basic tests metadata and allowlist upload endpoint
> feat(validations): allowlist upload, validations and tests

- src/pages/api/v1/web3up/allowlist.ts
* Refactor totalUnits in allowList API for easier parsing between HTTP clients
> feat(totalUnits): refactor to string

- next.config.js
> feat(cors): cors on app level

- next.config.js
- src/pages/api/v1/web3up/allowlist.ts
- src/pages/api/v1/web3up/metadata.ts
- src/utils/allowCors.ts
- src/utils/index.ts
> feat(cors): cors as middleware

- src/pages/api/v1/web3up/allowlist.ts
* bigint as string in typeguards
> fix(type): validate totalUnits as string input

- src/pages/api/v1/web3up/allowlist.ts
* get merkle object, not request input
> feat(merkle): get correct merkle object

- src/pages/api/v1/web3up/allowlist.ts
- src/pages/api/v1/web3up/metadata.ts
* error loggin for server side
> fix(err): err logging

- src/pages/api/v1/web3up/allowlist.ts
- src/pages/api/v1/web3up/metadata.ts
> fix(err): better err return

- src/pages/api/v1/web3up/allowlist.ts
- src/pages/api/v1/web3up/metadata.ts
* Upload and fetch Merkle Tree object as string
> fix(allowlist): upload as string

- .swcrc
- src/index.ts
* Update SWC config so that `import ... assert { type: json}` is not replace with `import ... with {type: json}`
> fix(build): swc respects assert json

- README.md
- RELEASE.md
- package.json
- src/graphql/schemas/resolvers/hypercertResolver.ts
- src/index.ts
- src/types/supabase.ts
* Updated Supabase types
* Added /health endpoint
Closes #15
> feat(health): added health endpoint and some cleanup

- src/__generated__/routes/routes.ts
- src/__generated__/swagger.json
- src/controllers/AllowListController.ts
- src/controllers/MetadataController.ts
- src/types/api.ts
- src/utils/parseAndValidateMerkleTreeDump.ts
- src/utils/validateMetadataAndClaimdata.ts
- src/utils/validateRemoteAllowList.ts
* Added endpoints to only validate data and get potential issues without uploading data
* Simplified parsing steps
* Added tags to group endpoints in Swagger
Closes #16
> feat(validate): validation endpoints and updated controllers

- schema.graphql
- src/client/graphql.ts
- src/controllers/AllowListController.ts
- src/graphql/schemas/enums/sortEnums.ts
- src/graphql/schemas/inputs/hypercertsInput.ts
- src/graphql/schemas/inputs/sortOptions.ts
- src/graphql/schemas/resolvers/attestationResolver.ts
- src/graphql/schemas/typeDefs/attestationTypeDefs.ts
- src/graphql/schemas/typeDefs/hypercertTypeDefs.ts
- src/graphql/schemas/utils/filters.ts
- src/graphql/schemas/utils/pagination.ts
- src/graphql/schemas/utils/sorting.ts
- src/index.ts
- src/services/SupabaseCachingService.ts
- src/types/graphql-env.d.ts
Fix field names returning null, fields no longer in db and other tweaks
> fix(fields): null fields and rename routes

- src/utils/jsonToBlob.ts
- src/utils/validateMetadataAndClaimdata.ts
* add `data` to validation return for uploading
> fix(data): return data from validation

- schema.graphql
- src/graphql/schemas/inputs/hypercertsInput.ts
- src/graphql/schemas/typeDefs/contractTypeDefs.ts
- src/graphql/schemas/typeDefs/fractionTypeDefs.ts
- src/graphql/schemas/typeDefs/hypercertTypeDefs.ts
- src/graphql/schemas/utils/filters.ts
- src/types/graphql-env.d.ts
Fixes:
- #78 
- #74 
Works on:
- #81
> fix(fields): filter contract and cleanup field names

- src/graphql/schemas/inputs/allowlistRecordsInput.ts
- src/graphql/schemas/inputs/sortOptions.ts
- src/graphql/schemas/typeDefs/allowlistRecordTypeDefs.ts
> fix(records): add root

- schema.graphql
- src/graphql/schemas/typeDefs/fractionTypeDefs.ts
- src/services/SupabaseCachingService.ts
- src/types/graphql-env.d.ts
* hypercert ID and fraction ID in fractions entity based on `fractions_view` in database
> fix(ids): hypercert and fraction ids in fraction type

- schema.graphql
- src/client/graphql.ts
- src/graphql/schemas/inputs/fractionInput.ts
- src/graphql/schemas/resolvers/fractionResolver.ts
- src/graphql/schemas/resolvers/hypercertResolver.ts
- src/graphql/schemas/resolvers/salesResolver.ts
- src/graphql/schemas/typeDefs/fractionTypeDefs.ts
- src/graphql/schemas/typeDefs/salesTypeDefs.ts
- src/services/SupabaseCachingService.ts
- src/types/graphql-env.d.ts
* Updated default query
* Fraction.sales response type to GetSalesResponse
* Removed redundant `_` from Field declarations
> fix(queries): jaaj

- schema.graphql
- src/graphql/schemas/typeDefs/allowlistRecordTypeDefs.ts
- src/graphql/schemas/typeDefs/attestationSchemaTypeDefs.ts
- src/graphql/schemas/typeDefs/attestationTypeDefs.ts
- src/graphql/schemas/typeDefs/collectionTypeDefs.ts
- src/graphql/schemas/typeDefs/contractTypeDefs.ts
- src/graphql/schemas/typeDefs/fractionTypeDefs.ts
- src/graphql/schemas/typeDefs/hypercertTypeDefs.ts
- src/graphql/schemas/typeDefs/metadataTypeDefs.ts
- src/graphql/schemas/typeDefs/orderTypeDefs.ts
- src/graphql/schemas/typeDefs/salesTypeDefs.ts
- src/types/graphql-env.d.ts
Fixes incorrect typing which led to mistyped Graph results
Was:
Is:
> fix(types): notorious BIG INT

- schema.graphql
- src/client/hypercerts.ts
- src/client/w3up.ts
- src/controllers/MetadataController.ts
- src/graphql/schemas/resolvers/salesResolver.ts
- src/graphql/schemas/typeDefs/salesTypeDefs.ts
- src/types/graphql-env.d.ts
- src/utils/jsonToBlob.ts
* Cleans up w3up updates
* Adds hypercerts with metadata field to sales typedef for easy fetching of hypercert data related to sale
> feat(gql): add hypercerts with metadata field to sales

- src/graphql/schemas/resolvers/orderResolver.ts
- src/services/SupabaseCachingService.ts
* update hypercert and metadata fetching calls in orderResolver
* fix incorrect join on metadata <> claims tables
> Order field resolver

- src/controllers/MetadataController.ts
Updates API to fix https://github.com/hypercerts-org/hypercerts-app/issues/200
> fix: attach cid to metadata instead of response object

- src/graphql/schemas/resolvers/attestationSchemaResolver.ts
- src/graphql/schemas/resolvers/contractResolver.ts
- src/graphql/schemas/resolvers/fractionResolver.ts
- src/graphql/schemas/resolvers/metadataResolver.ts
- src/graphql/schemas/resolvers/salesResolver.ts
Updates resolver responses to pass back object instead of handling returned data
> fix(resolver): pass back correct response object

- pnpm-lock.yaml
- src/services/SupabaseCachingService.ts
* Updates base resolver to query on `fractions_view` instead of `fractions` (which has column `hypercert_id`
> fix(fractions): query on fractions view with hypercert_id

- schema.graphql
- src/graphql/schemas/inputs/hypercertsInput.ts
- src/graphql/schemas/resolvers/baseTypes.ts
- src/graphql/schemas/typeDefs/baseTypes/hypercertBaseType.ts
- src/types/graphql-env.d.ts
* Allow returning and filtering on attestations and sales count
*Fix for filter updates related to https://github.com/hypercerts-org/hypercerts-app/issues/225
> feat(count): add sales and attestations count input and where filter

- schema.graphql
- src/graphql/schemas/inputs/allowlistRecordsInput.ts
- src/graphql/schemas/inputs/attestationInput.ts
- src/graphql/schemas/inputs/attestationSchemaInput.ts
- src/graphql/schemas/inputs/collectionInput.ts
- src/graphql/schemas/inputs/contractInput.ts
- src/graphql/schemas/inputs/fractionInput.ts
- src/graphql/schemas/inputs/hypercertsInput.ts
- src/graphql/schemas/inputs/metadataInput.ts
- src/graphql/schemas/inputs/orderInput.ts
- src/graphql/schemas/inputs/salesInput.ts
- src/graphql/schemas/inputs/searchOptions.ts
- src/graphql/schemas/inputs/whereOptions.ts
- src/graphql/schemas/utils/filters.ts
- src/types/graphql-env.d.ts
Create type for searching on integer as numberSearchOptions
Refactor numberSearchOptions to bigintSearchOptions
> fix(search): discern between bigint and integer search

- package.json
- pnpm-lock.yaml
- src/__generated__/routes/routes.ts
- src/__generated__/swagger.json
> feat: support filecoin calibration deployment

- .env.template
- README.md
- src/__generated__/routes/routes.ts
- src/__generated__/swagger.json
- src/instrument.mjs
* Setup instructions
* Architecture graph
* Notes, etc
> Update Readme 

- supabase/migrations/20241128201553_enable_realtime_order_tables.sql
Adds order tables to supabase realtime streams for cache invalidation
> Realtime order tables

- schema.graphql
- src/graphql/schemas/inputs/orderInput.ts
* Allows for filtering on invalidated orders
* Allows for filtering on currency address
> Add currency and invalidation status as filters

- scripts/blueprint_batch_mint.ts
- Introduced separate arrays for testnet and production chains for better organization, and because .testnet property is not always defined in viem.
- Updated chain selection logic to determine if the selected chain is a testnet based on the new structure.
> fix: refactor chain selection logic in blueprint_batch_mint.ts

- scripts/blueprint_batch_mint.ts
> Push to PRD

- package.json
- pnpm-lock.yaml
- src/__generated__/routes/routes.ts
- src/__generated__/swagger.json
- src/middleware/upload.ts
* Updates hypercerts SDK to 2.5.0-beta.3 to support geoJSON declarations in metadata properties
* Adds `application/geo+json` MIME type to UploadController `upload.ts` middleware
> geoJSON support

- src/controllers/MarketplaceController.ts
Fixes a regression introduced in
12f4e1f1ca47d7bb15eb3e16f4af233ce98c7ecf, which meant orders weren't fetched/awaited correctly when deleting an order, resulting in 404's.
> fix: order-deletion
