schema.graphql, src/client/graphql.ts, src/graphql/schemas/args/hypercertsArgs.ts, src/graphql/schemas/resolvers/hypercertResolver.ts, src/graphql/schemas/resolvers/metadataResolver.ts, src/graphql/schemas/typeDefs/hypercertTypeDefs.ts, src/services/SupabaseService.ts, src/types/graphql-env.d.ts
Updated the hypercertsresolver to only return a single metadata and contracts object since there should only be one per hypercert
=> fix(array): return maybeSingle for contract and metadata on hypercert

src/controllers/AllowListController.ts
Handler tried to make a dump of the allowlist entry array instead of uploading the data, resulting in 500s.
Fixed and uploaded an example list bafkreic3rmooknjyxw4knhyta4usodylcv4nb5l3gru7xqckrzaiw4mugu
=> fix(upload): upload provided data after validation

schema.graphql, src/graphql/schemas/args/allowlistRecordArgs.ts, src/graphql/schemas/inputs/allowlistRecordsInput.ts, src/graphql/schemas/inputs/orderOptions.ts, src/graphql/schemas/inputs/sortOptions.ts, src/graphql/schemas/resolvers/allowlistRecordResolver.ts, src/graphql/schemas/resolvers/composed.ts, src/graphql/schemas/typeDefs/allowlistRecordTypeDefs.ts, src/graphql/schemas/typeDefs/orderTypeDefs.ts, src/services/SupabaseCachingService.ts, src/types/graphql-env.d.ts, src/types/supabaseCaching.ts
Adds claimable allow list records to graph
```graphql
{
allowlistRecords(
count: COUNT
where: {user_address: {contains: "0x3506e5f79754e8aad83152b8e6189b6c5508aad4"}, claimed: {eq: false}}
) {
count
data {
claimed
entry
user_address
}
}
}
```
=> feat(records): add to graph with filter and sort

schema.graphql, src/graphql/schemas/inputs/salesInput.ts, src/graphql/schemas/inputs/searchOptions.ts, src/types/graphql-env.d.ts
Add fields to Sales typedef for querying sales: buyer, seller, etc..
=> fix(gql): add missing sales fields to typedefs

supabase/migrations/20240813175015_add_rls_policy_for_orders.sql
Updates latest migration to drop policy if it already exists
=> fix(migration): drop policy if already exists

src/graphql/schemas/args/baseArgs.ts, src/graphql/schemas/resolvers/attestationResolver.ts, src/graphql/schemas/resolvers/baseTypes.ts, src/graphql/schemas/resolvers/hypercertResolver.ts, src/graphql/schemas/resolvers/orderResolver.ts, src/graphql/schemas/resolvers/salesResolver.ts, src/graphql/schemas/typeDefs/allowlistRecordTypeDefs.ts, src/graphql/schemas/typeDefs/fractionTypeDefs.ts, src/graphql/schemas/typeDefs/hypercertTypeDefs.ts, src/graphql/schemas/typeDefs/metadataTypeDefs.ts, src/services/SupabaseCachingService.ts
When querying using filters, or when using pagination, count should not return the amount or returned rows, but the amount of rows matching the filter params.
This PR:
- Defines dataQuery and countQuery builder
- Implements data fetching buy calling both the data and count query in a single transaction
- Cleans up some business logic
=> Restore count

schema.graphql, src/graphql/schemas/typeDefs/baseTypes/hypercertBaseType.ts, src/types/graphql-env.d.ts
* Graphql automagically declares numbers as floats, we want ints, so made it explicit
=> fix(types): counts as ints not floats

.github/workflows/ci-test-unit.yml, package.json, pnpm-lock.yaml, src/__generated__/routes/routes.ts, src/__generated__/swagger.json, src/controllers/AllowListController.ts, src/controllers/BlueprintController.ts, src/controllers/HyperboardController.ts, src/controllers/MarketplaceController.ts, src/controllers/MetadataController.ts, src/controllers/UserController.ts, src/types/api.ts, test/api/v1/allowlist.test.ts, test/api/v1/metadata.test.ts, test/test-utils/mockMerkleTree.ts, test/test-utils/mockMetadata.ts, vitest.config.ts
* Updates allowlist and metadata controller test suites to use updated controller logic
* Updates allowlist and metadata controllers to have better error handling and cleaner types
* Updates other pieces of code affected by the type changes
* Adds coverage reporter
* Adds CI action for testing and test coverage reporting
=> Set up test suites and testing CI

schema.graphql, src/__generated__/routes/routes.ts, src/__generated__/swagger.json, src/graphql/schemas/args/attestationArgs.ts, src/graphql/schemas/inputs/attestationInput.ts, src/graphql/schemas/inputs/attestationSchemaInput.ts, src/graphql/schemas/resolvers/attestationResolver.ts, src/graphql/schemas/resolvers/attestationSchemaResolver.ts, src/graphql/schemas/resolvers/baseTypes.ts, src/graphql/schemas/typeDefs/attestationSchemaTypeDefs.ts, src/graphql/schemas/typeDefs/attestationTypeDefs.ts, src/graphql/schemas/typeDefs/baseTypes/attestationBaseType.ts, src/graphql/schemas/typeDefs/baseTypes/attestationSchemaBaseType.ts, src/graphql/schemas/utils/filters-kysely.ts, src/services/SupabaseCachingService.ts
This PR updates the attestation resolver so that you can query attestations based on EAS schema data like the `uid`
=> Attestation resolver with schemas

schema.graphql, src/graphql/schemas/args/collectionArgs.ts, src/graphql/schemas/inputs/collectionInput.ts, src/graphql/schemas/inputs/sortOptions.ts, src/graphql/schemas/resolvers/collectionResolver.ts, src/graphql/schemas/resolvers/composed.ts, src/graphql/schemas/typeDefs/collectionTypeDefs.ts, src/graphql/schemas/typeDefs/hyperboardTypeDefs.ts, src/graphql/schemas/utils/sorting.ts, src/index.ts, src/instrument.mjs, src/services/BaseSupabaseService.ts, src/services/SupabaseDataService.ts, src/utils/assertExists.ts, src/utils/constants.ts, src/utils/envVars.ts, test/safe-signatures/SafeSignatureVerifier.test.ts, test/utils/verifyAuthSignedData.test.ts, vitest.config.ts
Without this PR the user of our GraphQL endpoints needs to go via hyperboards to access the collections inside. Another drawback is that via this query they can only access the hypercert id, so they'll have to fire a separate query to combine the data.
This PR adds collections as a top level entity and exposes full hypercert objects as child entities. This also applies to hyperboards as the standalone collections entity is being reused there too.
This PR also provides a fix for hyperboard sorting.
Incidentally the tests around signature verification were broken, which blocked this PR. I refactored the tests to not rely on the Alchemy API key to fix the issues.
=> Create `collections` top level entity in GraphQL

src/controllers/MetadataController.ts
reverts a regression introduced in commit
4f6bebaac90bb030a97f9a4caaabd54e71620ec8 where we started checking for allowlist, instead of metadata.allowlist. We should actually check for the presence of metadata.allowlist, to prevent the case where the user specifies both a CID and a json allowlist to the endpoint.
=> fix: check for presence of metadata.allowlist instead of allowlist

src/graphql/schemas/resolvers/hypercertResolver.ts
- Replace throwing an error with console.error logging
- Return a default value when order fetching fails
=> fix: improve error handling in hypercert orders resolver

package.json, pnpm-lock.yaml, src/lib/safe/signature-verification/SafeSignatureVerifier.ts, src/lib/safe/signature-verification/SignatureVerifierStrategy.ts, vitest.config.ts
To support filecoin we need to bypass the SafeSDK to verify Safe signatures. The SafeSignatureVerifier class was updated to support different strategies based on chain ID. A SignatureVerifierFactory was implemented to either execute a contract call or use the Safe SDK depending on the provided chain ID.
=> Implement contract signature verification

src/graphql/schemas/resolvers/baseTypes.ts, src/graphql/schemas/resolvers/collectionResolver.ts, src/services/SupabaseDataService.ts, test/safe-signatures/SafeSignatureVerifier.test.ts, vitest.config.ts
Without this patch filtering doesn't work on collections. The following query returns all collections instead of the one that's filtered for:
```graphql
{
collections(where: { name: { eq: "test"}}) {
data {
name
id
hypercerts {
hypercert_id
}
}
}
}
```
The same holds true for ids.
=> fix(graphql): filter on collections not working

src/services/SupabaseCachingService.ts
Without specifying that `selectAll()` should give preference to columns present in the claims table, it ends up selecting fractions.units when the join is applied.
=> fix: select columns from correct table when filtering on fraction

src/instrument.mjs
As we're getting high loads on Sentry spans, we reduce the sampling rate from 1.0 to 0.1 for production and 1.0 on staging.
The reason for this is to primarily lower the amount of traces sent. However, we keep it 100% on staging to detect bugs and as traffic is lower there
Closing #270
=> chore(sentry): lower polling rates

src/services/SupabaseCachingService.ts
Fixes a bug where the schema_uid was not selected correctly, which resulted in errors when fetching eas_schema using graphql as it's non-nullable.
NOTE: Querying attestations by metadata is broken, as it was before. I spent some time trying to fix this but ran into issues. I think it would be more time-efficient to revisit that after https://github.com/hypercerts-org/hypercerts-api/pull/263 has been merged. That issue is related to nested inner joins, eg attestations joins claims joins metadata. Created https://github.com/hypercerts-org/hypercerts-api/issues/280 to track that.
=> fix: select correct columns when pulling attestations from db

src/__generated__/routes/routes.ts, src/__generated__/swagger.json, src/commands/CommandFactory.ts, src/commands/MarketplaceCreateOrderCommand.ts, src/controllers/MarketplaceController.ts, src/controllers/UserController.ts, src/lib/errors/controller.ts, src/lib/errors/request-parsing.ts, src/lib/marketplace/EOACreateOrderStrategy.ts, src/lib/marketplace/MarketplaceStrategy.ts, src/lib/marketplace/MarketplaceStrategyFactory.ts, src/lib/marketplace/MultisigCreateOrderStrategy.ts, src/lib/marketplace/errors.ts, src/lib/marketplace/request-parser.ts, src/lib/marketplace/schemas.ts, src/lib/safe/signature-verification/MarketplaceCreateOrderSignatureVerifier.ts, src/lib/users/MultisigUpsertStrategy.ts, src/lib/users/errors.ts, src/types/api.ts, src/types/supabaseData.ts, supabase/migrations/20250328123629_update_signature_request_purpose.sql, test/lib/marketplace/request-parser.test.ts, vitest.config.ts
This PR adds support for creating marketplace listings from your Safe. 
It therefore changes the payload structure for the `POST /marketplace/orders` request to expect a discriminated union of either the EOA request or the multisig request. For backwards compatibility the previous request structure is also supported.
My recommendation would be to ship this PR and the [Hypercerts SDK PR](https://github.com/hypercerts-org/hypercerts-sdk/pull/39) first, update the app to point to the new SDK version and test the review build there.
=> Safe integration marketplace listings

src/controllers/MonitoringController.ts
A version prefix is now required on the monitoring endpoint, so that both versions of the api can be monitored separately behind the nginx reverse proxy.
=> fix: add version prefix to health monitoring endpoint

schema.graphql, src/graphql/schemas/typeDefs/baseTypes/hypercertBaseType.ts, src/graphql/schemas/typeDefs/fractionTypeDefs.ts, src/lib/graphql/whereFieldDefinitions.ts, src/services/database/entities/HypercertsEntityService.ts, src/services/database/strategies/ClaimsQueryStrategy.ts, src/services/database/strategies/QueryStrategyFactory.ts, src/services/graphql/resolvers/hyperboardResolver.ts, src/types/supabaseCaching.ts, test/services/database/strategies/ClaimsQueryStrategy.test.ts
- Introduced a 'burned' Boolean field to AllowlistRecordHypercertWhereInput, AttestationHypercertWhereInput, CollectionHypercertWhereInput, Fraction, Hypercert, HypercertBaseType, and several other input types.
- Updated FractionSortOptions and HypercertSortOptions to include sorting by 'burned'.
- Enhanced database entity definitions to accommodate the new 'burned' field in relevant tables and views.
=> feat(graphql): add 'burned' field to various types and inputs
